export const COURSE_REGISTED_REQUEST = 'COURSE_REGISTED_REQUEST'
export const COURSE_REGISTED_SUCCESS = 'COURSE_REGISTED_SUCCESS'
export const COURSE_REGISTED_FAIL = 'COURSE_REGISTED_FAIL'

export const COURSE_WAITTING_REQUEST = 'COURSE_WAITTING_REQUEST'
export const COURSE_WAITTING_SUCCESS = 'COURSE_WAITTING_SUCCESS'
export const COURSE_WAITTING_FAIL = 'COURSE_WAITTING_FAIL'

