export const UPDATE_DETAIL_REQUEST = 'UPDATE_DETAIL_REQUEST'
export const UPDATE_DETAIL_SUCCESS = 'UPDATE_DETAIL_SUCCESS'
export const UPDATE_DETAIL_FAIL = 'UPDATE_DETAIL_FAIL'
export const CLEAR_NOTE = 'CLEAR_NOTE'

