export const DETAIL_REQUEST = 'DETAIL_REQUEST'
export const DETAIL_SUCCESS = 'DETAIL_SUCCESS'
export const DETAIL_FAIL = 'DETAIL_FAIL'

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL'

